# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of WireGuard Easy systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wg_easy_identifier }}.service"
  register: wg_easy_service_stat

- name: Uninstall WireGuard Easy systemd services and files
  when: wg_easy_service_stat.stat.exists | bool
  block:
    - name: Ensure WireGuard Easy systemd service is stopped
      ansible.builtin.service:
        name: "{{ wg_easy_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure WireGuard Easy systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wg_easy_identifier }}.service"
        state: absent

    - name: Ensure WireGuard Easy path does not exist
      ansible.builtin.file:
        path: "{{ wg_easy_base_path }}"
        state: absent
